#!/bin/sh
# Backs up the given files (under $HOME) before something changes them, and
# writes a restore.sh next to the copies. Files that do not exist yet are
# recorded as "absent": restoring deletes them again.
#
#   sh hyde-backup.sh FILE...
#   sh ~/.local/share/quicy-backups/latest/restore.sh     # undo
#
# Only regular files and symlinks are supported; directories are refused so a
# restore can never delete or overwrite a whole tree.
set -eu

[ $# -gt 0 ] || { echo "usage: $0 FILE..." >&2; exit 2; }
[ -n "${HOME:-}" ] || { echo "HOME is not set" >&2; exit 2; }

# Single-quote a string for the generated script.
q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

# Validate everything before creating anything, so a refusal leaves no backup.
for f in "$@"; do
  case "$f" in
    "$HOME"/*) ;;
    *) echo "refusing path outside \$HOME: $f" >&2; exit 2 ;;
  esac
  case "/$f/" in
    */../*) echo "refusing path with '..': $f" >&2; exit 2 ;;
  esac
  if [ -d "$f" ] && [ ! -L "$f" ]; then
    echo "refusing directory: $f" >&2; exit 2
  fi
done

root="${QUICY_BACKUP_DIR:-$HOME/.local/share/quicy-backups}"
n=0
while :; do
  dir="$root/$(date +%Y%m%d-%H%M%S)-$n"
  mkdir -p "$root" && mkdir "$dir" 2>/dev/null && break
  n=$((n + 1))
done
mkdir -p "$dir/files"
restore="$dir/restore.sh"
printf '#!/bin/sh\n# Generated by hyde-backup.sh: puts the backed-up files back.\nset -eu\n' > "$restore"

for f in "$@"; do
  rel=${f#"$HOME"/}
  parent=$(dirname "$f")
  if [ -L "$f" ]; then
    printf 'mkdir -p %s && ln -sfn %s %s\n' "$(q "$parent")" "$(q "$(readlink "$f")")" "$(q "$f")" >> "$restore"
  elif [ -e "$f" ]; then
    mkdir -p "$dir/files/$(dirname "$rel")"
    cp -p "$f" "$dir/files/$rel"
    printf 'mkdir -p %s && rm -f %s && cp -p %s %s\n' "$(q "$parent")" "$(q "$f")" "$(q "$dir/files/$rel")" "$(q "$f")" >> "$restore"
  else
    # rm -f only touches files and links, so a directory that appeared here is left alone.
    printf 'if [ -f %s ] || [ -L %s ]; then rm -f %s; fi\n' "$(q "$f")" "$(q "$f")" "$(q "$f")" >> "$restore"
  fi
done

chmod +x "$restore"
ln -sfn "$dir" "$root/latest"
echo "Backup saved in $dir"
echo "Restore with: sh $root/latest/restore.sh"
