#!/bin/sh
# Undoes install.sh: restores the files and dconf settings saved by the
# install (this also removes the template again) and deletes the generated
# theme. Use a different backup with: sh uninstall.sh BACKUP_DIR
#
# It does not touch ~/.config/hyde/config.toml; if you added a QuiCy bar entry
# there, restore your own backup of that file (see INSTALL.md).
set -eu

[ -n "${HOME:-}" ] || { echo "HOME is not set" >&2; exit 2; }
root="${QUICY_BACKUP_DIR:-$HOME/.local/share/quicy-backups}"
backup="${1:-$root/install}"
restore="$backup/restore.sh"

[ -f "$restore" ] || { echo "no install backup found at $backup (nothing changed)" >&2; exit 1; }
# Only run scripts that hyde-backup.sh wrote.
[ "$(sed -n 2p "$restore")" = "# Generated by hyde-backup.sh: puts the backed-up files back." ] || {
  echo "$restore was not written by hyde-backup.sh, refusing to run it" >&2; exit 1; }

sh "$restore"

# The install link has done its job; the next install starts a new one.
if [ -L "$root/install" ] && [ "$(readlink -f "$root/install")" = "$(readlink -f "$backup")" ]; then
  rm -f "$root/install"
fi

state="$HOME/.local/state/quicy"
rm -f "$state/theme.json"
# rmdir only removes an empty directory: anything else in there is not ours.
rmdir "$state" 2>/dev/null || true
echo "QuiCy's HyDE hook is removed and the saved state is restored."
